/**
 * Generates the PWA / home-screen icon set (and the SVG favicon) for NOISE WALL.
 *
 * Pure Node — no image libraries, no network: a tiny PNG encoder on top of
 * `node:zlib`, plus a deterministic renderer for the app's waveform motif
 * (nine bars of red noise on near-black). Deterministic output means the
 * committed icons can be regenerated byte-for-byte:
 *
 *   npm run icons
 */

import { deflateSync } from 'node:zlib';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const publicDir = resolve(root, 'public');

// ─── Minimal PNG encoder ───

const CRC_TABLE = (() => {
  const table = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    table[n] = c >>> 0;
  }
  return table;
})();

function crc32(buffer) {
  let crc = 0xffffffff;
  for (let i = 0; i < buffer.length; i++) crc = CRC_TABLE[(crc ^ buffer[i]) & 0xff] ^ (crc >>> 8);
  return (crc ^ 0xffffffff) >>> 0;
}

function pngChunk(type, data) {
  const length = Buffer.alloc(4);
  length.writeUInt32BE(data.length, 0);
  const typeAndData = Buffer.concat([Buffer.from(type, 'ascii'), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(typeAndData), 0);
  return Buffer.concat([length, typeAndData, crc]);
}

/** Encodes raw RGBA bytes as a PNG buffer. */
function encodePNG(width, height, rgba) {
  const signature = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 6; // colour type: RGBA
  ihdr[10] = 0; // deflate
  ihdr[11] = 0; // adaptive filtering
  ihdr[12] = 0; // no interlace

  const stride = width * 4;
  const raw = Buffer.alloc((stride + 1) * height);
  for (let y = 0; y < height; y++) {
    raw[y * (stride + 1)] = 0; // filter: none
    rgba.copy(raw, y * (stride + 1) + 1, y * stride, (y + 1) * stride);
  }

  return Buffer.concat([
    signature,
    pngChunk('IHDR', ihdr),
    pngChunk('IDAT', deflateSync(raw, { level: 9 })),
    pngChunk('IEND', Buffer.alloc(0)),
  ]);
}

// ─── Drawing ───

function createCanvas(size) {
  const pixels = Buffer.alloc(size * size * 4);
  // Base: near-black with a faint vertical tint, alpha 255.
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      const i = (y * size + x) * 4;
      const vignette = Math.max(0, 1 - Math.hypot(x / size - 0.5, y / size - 0.5) * 1.15);
      pixels[i] = Math.round(8 + 14 * vignette);
      pixels[i + 1] = Math.round(8 + 6 * vignette);
      pixels[i + 2] = Math.round(14 + 22 * vignette);
      pixels[i + 3] = 255;
    }
  }
  return pixels;
}

function fillRect(pixels, size, x0, y0, w, h, [r, g, b], alpha = 1) {
  const left = Math.max(0, Math.round(x0));
  const top = Math.max(0, Math.round(y0));
  const right = Math.min(size, Math.round(x0 + w));
  const bottom = Math.min(size, Math.round(y0 + h));
  for (let y = top; y < bottom; y++) {
    for (let x = left; x < right; x++) {
      const i = (y * size + x) * 4;
      pixels[i] = Math.round(pixels[i] * (1 - alpha) + r * alpha);
      pixels[i + 1] = Math.round(pixels[i + 1] * (1 - alpha) + g * alpha);
      pixels[i + 2] = Math.round(pixels[i + 2] * (1 - alpha) + b * alpha);
    }
  }
}

/** Nine bars of "noise", the same silhouette the app draws. */
const BAR_HEIGHTS = [0.3, 0.55, 0.82, 0.44, 0.95, 0.66, 0.38, 0.78, 0.5];

function drawMotif(pixels, size, inset) {
  const box = size * (1 - inset * 2);
  const originX = size * inset;
  const originY = size * inset;
  const bars = BAR_HEIGHTS.length;
  const gap = box * 0.045;
  const barWidth = (box - gap * (bars - 1)) / bars;
  const centerY = originY + box / 2;

  for (let b = 0; b < bars; b++) {
    const height = box * BAR_HEIGHTS[b];
    const x = originX + b * (barWidth + gap);
    const y = centerY - height / 2;
    // Vertical gradient per bar: #ef4444 at the top → #7f1d1d at the bottom.
    const steps = Math.max(1, Math.round(height));
    for (let s = 0; s < steps; s++) {
      const t = s / steps;
      const color = [
        Math.round(239 * (1 - t) + 127 * t),
        Math.round(68 * (1 - t) + 29 * t),
        Math.round(68 * (1 - t) + 29 * t),
      ];
      fillRect(pixels, size, x, y + s, barWidth, 1.2, color);
    }
  }
}

function renderIcon(size, { inset = 0.16 } = {}) {
  const pixels = createCanvas(size);
  drawMotif(pixels, size, inset);

  // Top-edge highlight so the tile reads as "lit" on a dark home screen.
  fillRect(pixels, size, size * 0.14, size * 0.07, size * 0.72, Math.max(1, size * 0.006), [239, 68, 68], 0.5);
  return encodePNG(size, size, pixels);
}

// ─── Output ───

const faviconSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64">
  <rect width="64" height="64" rx="12" fill="#08080e"/>
  ${BAR_HEIGHTS.map((h, index) => {
    const gap = 2.4;
    const barWidth = (44 - gap * (BAR_HEIGHTS.length - 1)) / BAR_HEIGHTS.length;
    const x = 10 + index * (barWidth + gap);
    const barHeight = 40 * h;
    return `<rect x="${x.toFixed(2)}" y="${(32 - barHeight / 2).toFixed(2)}" width="${barWidth.toFixed(2)}" height="${barHeight.toFixed(
      2,
    )}" rx="1" fill="#dc2626"/>`;
  }).join('\n  ')}
</svg>
`;

mkdirSync(publicDir, { recursive: true });
writeFileSync(resolve(publicDir, 'icon-192.png'), renderIcon(192));
writeFileSync(resolve(publicDir, 'icon-512.png'), renderIcon(512));
// Maskable icons need their content inside the safe zone (centre 80%).
writeFileSync(resolve(publicDir, 'icon-maskable-512.png'), renderIcon(512, { inset: 0.26 }));
writeFileSync(resolve(publicDir, 'apple-touch-icon.png'), renderIcon(180, { inset: 0.18 }));
writeFileSync(resolve(publicDir, 'favicon.svg'), faviconSvg);

console.log('Wrote public/icon-192.png, icon-512.png, icon-maskable-512.png, apple-touch-icon.png, favicon.svg');
