/**
 * Renders `docs/assets/launch-qr.svg` — a scannable QR code for the deployed
 * app, so a phone can be pointed at a laptop screen and be playing a wall
 * seconds later.
 *
 *   npm run qr
 *
 * Override the target when deploying somewhere other than GitHub Pages:
 *   NOISE_WALL_URL=https://noise.example.dev/ npm run qr
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import QRCode from 'qrcode';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const url =
  process.env.NOISE_WALL_URL ??
  'https://zazieproductions.github.io/interactive-harsh-noise-generator/';

const svg = await QRCode.toString(url, {
  type: 'svg',
  errorCorrectionLevel: 'M',
  margin: 2,
  width: 320,
  color: { dark: '#0a0a12', light: '#ffffff' },
});

const outDir = resolve(root, 'docs/assets');
mkdirSync(outDir, { recursive: true });
writeFileSync(
  resolve(outDir, 'launch-qr.svg'),
  `<!-- Generated by scripts/generate-qr.mjs — do not edit by hand. Target: ${url} -->\n${svg}`,
);

console.log(`Wrote docs/assets/launch-qr.svg for ${url}`);
